// ---------------------------------------------------------------------------
// Design work — collections and helpers
// ---------------------------------------------------------------------------
// Image entries come from app/lib/gallery.json, generated by `npm run gallery`
// from the raw files in "Portofolio (by Folder)". Edit collection copy here.
// ---------------------------------------------------------------------------

import manifest from "./gallery.json";

export type GalleryItem = {
  id: string;
  collection: string;
  brand: string;
  group: string | null;
  title: string | null;
  tag: string | null;
  width: number;
  height: number;
  /** Full-page screenshot: thumb is cropped to the top, lightbox scrolls. */
  tall: boolean;
  thumb: string;
  full: string;
};

export type CollectionGroup = "graphic" | "uiux" | "video";

export const collectionGroups: { id: CollectionGroup; title: string; summary: string }[] = [
  {
    id: "graphic",
    title: "Graphic design",
    summary: "Print and digital visuals for consumer brands.",
  },
  {
    id: "uiux",
    title: "UI/UX design",
    summary: "App and web interfaces designed in Figma.",
  },
  {
    id: "video",
    title: "Video editing",
    summary: "Short-form social videos and longer edits.",
  },
];

export type Collection = {
  slug: string;
  group: CollectionGroup;
  title: string;
  /** One line under the title on the overview tile. */
  summary: string;
  /** Longer intro on the collection page. */
  intro: string;
  /** Aspect ratio of most pieces — controls grid density. */
  ratio: "square" | "portrait" | "story" | "wide" | "video";
  /** Substring of the file path used as the overview cover; defaults to the first item. */
  cover?: string;
  /** Use a designed cover from "College/Cover Website" instead (filename fragment). */
  coverFrom?: string;
  /** External design file, shown as a button on the collection page. */
  figma?: string;
  /** Extra buttons on the collection page (live site, docs, related page). */
  links?: { href: string; label: string }[];
};

export const collections: Collection[] = [
  // --- Graphic design -----------------------------------------------------
  {
    slug: "marketplace",
    group: "graphic",
    title: "Marketplace listings",
    summary: "Product image sets for Shopee and Tokopedia storefronts.",
    intro:
      "Listing images for a health-supplement brand — hero shots, benefit call-outs, size variants, and gift bundles. Each product ships as a coordinated set so the storefront reads as one brand.",
    ratio: "square",
    cover: "calmagzinc-1",
  },
  {
    slug: "catalog",
    group: "graphic",
    title: "Product catalog",
    summary: "Single-page product sheets for the full supplement range.",
    intro:
      "A page per product: packaging photography, key benefits, and nutritional tables laid out on a shared grid so the catalog stays consistent across the whole range.",
    ratio: "portrait",
    cover: "colostrum",
  },
  {
    slug: "packaging",
    group: "graphic",
    title: "Packaging",
    summary: "Print-ready dielines for supplement boxes.",
    intro:
      "Box dielines prepared for print — front, back, and side panels with composition tables, usage directions, and regulatory marks in place.",
    ratio: "wide",
  },
  {
    slug: "instagram-feeds",
    group: "graphic",
    title: "Instagram feeds",
    summary: "Campaign posts and holiday greetings for three brands.",
    intro:
      "Feed posts for three brands: seasonal greetings and recruitment posts for a supplement company, sale campaigns for a fashion label, and promos for a retail store.",
    ratio: "square",
    cover: "1677723121859",
  },
  {
    slug: "instagram-stories",
    group: "graphic",
    title: "Instagram stories",
    summary: "Vertical story graphics for campaigns and holidays.",
    intro:
      "Full-height story graphics built for the phone screen — product launches, promos, and holiday greetings.",
    ratio: "story",
    cover: "tahun-baru-islam-story",
  },
  {
    slug: "lorikeet",
    group: "graphic",
    title: "Lorikeet",
    summary: "Themed nine-post Instagram grids that read as one image on the profile.",
    intro:
      "Lorikeet grids: nine feed posts planned as a single composition, so the brand's profile page shows one themed image while each post still works on its own. One for a fashion label's new-arrival campaign, one for a parenting-education brand concept.",
    ratio: "wide",
    cover: "gykaco",
  },
  {
    slug: "campus-design",
    group: "graphic",
    title: "Campus design work",
    summary: "Brand concept and infographic for a university project.",
    intro:
      "Design pieces from coursework. BabyBloom is a digital parenting-education brand concept — this business infographic covers its SDG focus, mind map, and value proposition canvas.",
    ratio: "wide",
    cover: "infographic",
  },

  {
    slug: "just-for-fun",
    group: "graphic",
    title: "Just for fun",
    summary: "Personal Photoshop pieces — photo manipulation, glitch effects, and whatever caught my eye.",
    intro:
      "Made in spare time, for nobody but me. Photo manipulation is one of the hardest techniques in Photoshop to get right, and one of the most satisfying — these are the experiments that made it out of the drafts folder.",
    ratio: "square",
    cover: "photo-manipulation",
  },

  // --- UI/UX design -------------------------------------------------------
  {
    slug: "pantryhub",
    group: "uiux",
    title: "PantryHub",
    summary: "Mobile app for household pantry stock, recipes, and grocery ordering — four user roles.",
    intro:
      "A mobile app that connects households, restaurants, and supermarkets around food stock. Every role gets its own flow — sign-up, stock and category management, recipe recommendations, ordering and checkout, chat, and support — designed screen by screen in Figma.",
    ratio: "story",
    cover: "4-main-menu",
    figma: "https://www.figma.com/design/sCMRRVYBxw3whkq4M4Kp6S/Pantry-Hub?node-id=0-1&t=25BJkwDLAqxFazgy-1",
  },
  {
    slug: "promohub",
    group: "uiux",
    title: "PromoHub",
    summary: "Web platform for discovering merchant promos and redeeming points.",
    intro:
      "A promo-discovery website: homepage, search and category browsing, merchant pages, descriptions, reviews, bookmarks, and a points-redemption system. Each page is shown as a full-length screenshot — open one and scroll.",
    ratio: "portrait",
    cover: "homepage",
    figma: "https://www.figma.com/design/wNal59Oi4BQqvtKc4y1eKd/PromoHub?node-id=0-1&t=WJ96XSAnhdGJ8Do8-1",
  },
  {
    slug: "portfoliox",
    group: "uiux",
    title: "PortfolioX",
    summary: "Investment portfolio platform — dashboard, simulation, optimisation, and risk profiling. Shipped to production.",
    intro:
      "Software Engineering group project, built and deployed as a real product. PortfolioX helps investors manage a portfolio, run Monte Carlo simulations against the efficient frontier, optimise allocations with mean-variance optimisation, and profile their risk. I owned the UI/UX design, worked on the FastAPI backend, and helped write the documentation. Website pages first, then the mobile layout.",
    ratio: "portrait",
    cover: "01-homepage",
    figma: "https://www.figma.com/design/Iab0DNkJIKDZ4HHT1eIYFb/PORTOFOLIOX?node-id=0-1&t=sXpFrzlpnrPG9y5P-1",
    links: [
      { href: "https://portfoliox-se.vercel.app/", label: "Open live site" },
      { href: "https://github.com/Software-Engineering-LD01/PortfolioX", label: "Source on GitHub" },
      {
        href: "https://app.notion.com/p/PORTFOLIOX-Software-Engineering-Project-Documentation-fb39690328d94aa1a3a35e884eeb1867",
        label: "Read the documentation",
      },
    ],
  },
  {
    slug: "mrcoffee",
    group: "uiux",
    title: "Mr. Coffee (Figma)",
    summary: "Coffee shop website, pure Figma version — menu, ordering, and rewards.",
    intro:
      "Human–Computer Interaction final project. The brief asked for two versions of the same coffee-shop website with deliberately different designs: this one is the pure Figma prototype — homepage, about, menu, ordering with confirmation, rewards with its pop-up states, and the component sheet. The second version was built in HTML.",
    ratio: "portrait",
    cover: "homepage",
    figma: "https://www.figma.com/design/HF0iNdOkwynnils0GUmC6n/Mr.-Coffee?node-id=0-1&t=iFdL6miEJ6P07REj-1",
    links: [{ href: "/design/mrcoffee-html", label: "See the HTML version" }],
  },
  {
    slug: "mrcoffee-html",
    group: "uiux",
    title: "Mr. Coffee (HTML)",
    summary: "Coffee shop website, second version — designed in Figma and built with HTML, CSS, and JavaScript.",
    intro:
      "The second version from the same HCI final project, with its own design direction. This one went past the prototype: designed in Figma, then coded by hand in HTML, CSS, and JavaScript — homepage, about, per-category menu pages, promos, and the ordering flow.",
    ratio: "portrait",
    cover: "homepage",
    figma: "https://www.figma.com/design/OBxRyVD43WWjfuHqyzY7QZ/Mr.-Coffee-HTML?node-id=0-1&t=P61Ic6s7A1B8vtdP-1",
    links: [{ href: "/design/mrcoffee", label: "See the Figma version" }],
  },
  {
    slug: "aivi",
    group: "uiux",
    title: "AIVI",
    summary: "AI health check-up analysis — landing, sign-in, and results dashboard.",
    intro:
      "AIVI reads a user's general check-up data — blood pressure, glucose, cholesterol — and returns instant, AI-generated health recommendations. Landing page, authentication, and the main results page, in light mode.",
    ratio: "portrait",
    coverFrom: "aivi-design",
    figma: "https://www.figma.com/design/0J8k5zyqXkrCeyL0paKPHP/AIVI?node-id=0-1&t=mZSh7LaK4zz2sezC-1",
  },

  // --- Video --------------------------------------------------------------
  {
    slug: "video",
    group: "video",
    title: "Video editing",
    summary: "Short-form product videos for two brands, two longer course projects, and freelance work.",
    intro:
      "Edited videos: short vertical product videos for a fashion label and a health-supplement brand's social channels, two longer final-project videos from university coursework, and freelance work.",
    ratio: "video",
  },
];

/** External links attached to individual pieces, matched on the file path. */
export const itemLinks: { match: string; href: string; label: string }[] = [
  {
    match: "lorikeet-babybloom",
    href: "https://www.instagram.com/by.babybloom",
    label: "See it live on Instagram",
  },
];

export function linkFor(item: GalleryItem) {
  return itemLinks.find((l) => item.full.includes(l.match));
}

export type Video = {
  title: string;
  youtubeId: string;
  /** Vertical short or standard 16:9 video. */
  kind: "short" | "video";
};

export const videoGroups: { label: string; videos: Video[] }[] = [
  {
    label: "Gykaco — short-form",
    videos: [
      { title: "Pick The Right One", youtubeId: "Halw9M7ApsI", kind: "short" },
      { title: "Pick Your Style", youtubeId: "Rv1mtdKxOWY", kind: "short" },
      { title: "Virgo", youtubeId: "YuJ8c8LeiOE", kind: "short" },
      { title: "Choose", youtubeId: "lfePv0r9unI", kind: "short" },
      { title: "Complete Her Look", youtubeId: "ItW683NHGhg", kind: "short" },
      { title: "Color", youtubeId: "8jkTJvnu8g8", kind: "short" },
      { title: "Handbag", youtubeId: "w0nuPiNAhug", kind: "short" },
      { title: "Pick Your Favourite", youtubeId: "MrjQFPRuY50", kind: "short" },
      { title: "Pick Your Clutch", youtubeId: "x_07cIsjJcw", kind: "short" },
      { title: "Pick Model Style", youtubeId: "JDzQ4C2VJyw", kind: "short" },
      { title: "Name The Style", youtubeId: "KIoKyonGB80", kind: "short" },
      { title: "Magnifier", youtubeId: "beloiyvELOQ", kind: "short" },
    ],
  },
  {
    label: "Daily Health — product videos",
    videos: [
      { title: "AmbeHeal", youtubeId: "ZMCu1txQyTI", kind: "short" },
      { title: "Vitamin D3+K2", youtubeId: "ZPpO1JQkS2E", kind: "short" },
      { title: "Visidat", youtubeId: "TaT7_1tiN44", kind: "short" },
      { title: "Sunny Kids", youtubeId: "0t-j83s6S90", kind: "short" },
      { title: "Oxi-T", youtubeId: "EMTs3HriI7Q", kind: "short" },
      { title: "Maaginto", youtubeId: "NdB6J2IxXao", kind: "short" },
      { title: "Ikan Gabus", youtubeId: "TZZi-N6-NRg", kind: "short" },
      { title: "Glucosamine", youtubeId: "0c0_v3hGHHk", kind: "short" },
      { title: "CalMagZinc", youtubeId: "QUkoSuszZGA", kind: "short" },
      { title: "Colostrum", youtubeId: "CbP2b6L2J50", kind: "short" },
    ],
  },
  {
    label: "Campus — final projects",
    videos: [
      // TODO(michael): give these friendlier titles if you like.
      { title: "Character Building: Kewarganegaraan", youtubeId: "1HMcuW2OFgA", kind: "video" },
      { title: "Character Building: Agama", youtubeId: "0va3vDbENNs", kind: "video" },
    ],
  },
  {
    label: "Freelance",
    videos: [
      // TODO(michael): name the client or the kind of video.
      { title: "Freelance project", youtubeId: "oiiiQ0qkgGA", kind: "short" },
    ],
  },
];

export const videos: Video[] = videoGroups.flatMap((g) => g.videos);

const items = manifest.items as GalleryItem[];

export function itemsFor(slug: string): GalleryItem[] {
  return items.filter((i) => i.collection === slug);
}

export function countFor(slug: string): number {
  return slug === "video" ? videos.length : itemsFor(slug).length;
}

export function coverFor(c: Collection): GalleryItem | undefined {
  if (c.coverFrom) {
    const designed = itemsFor("dev-screens").find((i) => i.full.includes(c.coverFrom as string));
    if (designed) return designed;
  }
  const list = itemsFor(c.slug);
  if (c.cover) {
    const hit = list.find((i) => i.full.includes(c.cover as string));
    if (hit) return hit;
  }
  return list[0];
}

/** YouTube poster for the video collection tile. */
export function videoCover(): string | undefined {
  const first = videos.find((v) => v.youtubeId);
  return first ? `https://i.ytimg.com/vi/${first.youtubeId}/hqdefault.jpg` : undefined;
}

export function brandsFor(slug: string): string[] {
  if (slug === "video") return videoGroups.map((g) => g.label.split(" — ")[0]);
  return [...new Set(itemsFor(slug).map((i) => i.brand))];
}

export function collectionsIn(group: CollectionGroup): Collection[] {
  return collections.filter((c) => c.group === group);
}

export function collectionBySlug(slug: string): Collection | undefined {
  return collections.find((c) => c.slug === slug);
}

/** Display title for a piece — falls back to "<brand> nn" for untitled exports. */
export function itemTitle(item: GalleryItem, index: number): string {
  return item.title ?? `${item.brand} ${String(index + 1).padStart(2, "0")}`;
}

/** Only the design division's collections — development screens live in the same manifest. */
export const totalDesignPieces =
  collections.reduce((n, c) => n + (c.slug === "video" ? 0 : itemsFor(c.slug).length), 0) +
  videos.length;

/** Screenshot for a development project card: matched by filename in the given collections. */
export function screenFor(match: string, collections: string[] = ["dev-screens"]): GalleryItem | undefined {
  for (const slug of collections) {
    const hit = itemsFor(slug).find((i) => i.full.includes(match));
    if (hit) return hit;
  }
  return undefined;
}
