// ---------------------------------------------------------------------------
// Design work — collections and helpers
// ---------------------------------------------------------------------------
// Image entries come from app/lib/gallery.json, generated by `npm run gallery`
// from the raw files in "Portofolio (by Folder)". Edit collection copy here.
// ---------------------------------------------------------------------------

import manifest from "./gallery.json";

export type GalleryItem = {
  id: string;
  collection: string;
  brand: string;
  group: string | null;
  title: string | null;
  tag: string | null;
  width: number;
  height: number;
  thumb: string;
  full: string;
};

export type Collection = {
  slug: string;
  title: string;
  /** One line under the title on the overview tile. */
  summary: string;
  /** Longer intro on the collection page. */
  intro: string;
  /** Aspect ratio of most pieces — controls grid density. */
  ratio: "square" | "portrait" | "story" | "wide" | "video";
  /** Substring of the file path used as the overview cover; defaults to the first item. */
  cover?: string;
};

export const collections: Collection[] = [
  {
    slug: "marketplace",
    title: "Marketplace listings",
    summary: "Product image sets for Shopee and Tokopedia storefronts.",
    intro:
      "Listing images for a health-supplement brand — hero shots, benefit call-outs, size variants, and gift bundles. Each product ships as a coordinated set so the storefront reads as one brand.",
    ratio: "square",
    cover: "colostrum-30-tablet-1",
  },
  {
    slug: "catalog",
    title: "Product catalog",
    summary: "Single-page product sheets for the full supplement range.",
    intro:
      "A page per product: packaging photography, key benefits, and nutritional tables laid out on a shared grid so the catalog stays consistent across the whole range.",
    ratio: "portrait",
    cover: "colostrum",
  },
  {
    slug: "packaging",
    title: "Packaging",
    summary: "Print-ready dielines for supplement boxes.",
    intro:
      "Box dielines prepared for print — front, back, and side panels with composition tables, usage directions, and regulatory marks in place.",
    ratio: "wide",
  },
  {
    slug: "instagram-feeds",
    title: "Instagram feeds",
    summary: "Campaign posts, holiday greetings, and a nine-tile puzzle grid.",
    intro:
      "Feed posts for two brands: seasonal greetings and recruitment posts for a supplement company, and sale campaigns for a fashion label — including a nine-tile puzzle grid that reads as one image on the profile.",
    ratio: "square",
    cover: "lorikeet",
  },
  {
    slug: "instagram-stories",
    title: "Instagram stories",
    summary: "Vertical story graphics for campaigns and holidays.",
    intro:
      "Full-height story graphics built for the phone screen — product launches, promos, and holiday greetings.",
    ratio: "story",
  },
  {
    slug: "video",
    title: "Video",
    summary: "Short-form product videos for social media.",
    intro:
      "Short vertical videos for a fashion label's social channels — product reveals, style picks, and campaign teasers.",
    ratio: "video",
  },
];

// Short videos — hosted on YouTube. TODO(michael): paste each video's
// YouTube ID (the part after `v=`), e.g. "dQw4w9WgXcQ".
export const videos: { title: string; youtubeId: string }[] = [
  { title: "Choose", youtubeId: "" },
  { title: "Color", youtubeId: "" },
  { title: "Complete Her Look", youtubeId: "" },
  { title: "Handbag", youtubeId: "" },
  { title: "Magnifier", youtubeId: "" },
  { title: "Name The Style", youtubeId: "" },
  { title: "Pick Model Style", youtubeId: "" },
  { title: "Pick The Right One", youtubeId: "" },
  { title: "Pick Your Clutch", youtubeId: "" },
  { title: "Pick Your Favourite", youtubeId: "" },
  { title: "Pick Your Style", youtubeId: "" },
  { title: "Virgo", youtubeId: "" },
];

const items = manifest.items as GalleryItem[];

export function itemsFor(slug: string): GalleryItem[] {
  return items.filter((i) => i.collection === slug);
}

export function countFor(slug: string): number {
  return slug === "video" ? videos.length : itemsFor(slug).length;
}

export function coverFor(c: Collection): GalleryItem | undefined {
  const list = itemsFor(c.slug);
  if (c.cover) {
    const hit = list.find((i) => i.full.includes(c.cover as string));
    if (hit) return hit;
  }
  return list[0];
}

export function brandsFor(slug: string): string[] {
  return [...new Set(itemsFor(slug).map((i) => i.brand))];
}

export function collectionBySlug(slug: string): Collection | undefined {
  return collections.find((c) => c.slug === slug);
}

/** Display title for a piece — falls back to "<brand> · n" for untitled exports. */
export function itemTitle(item: GalleryItem, index: number): string {
  return item.title ?? `${item.brand} ${String(index + 1).padStart(2, "0")}`;
}

export const totalDesignPieces = items.length + videos.length;
